version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.macOS
    tty: true
    volumes:
      - ./data/:/app/data
      - ./notebooks/:/app/notebooks
      - ./scripts/:/app/scripts
    ports:
        - "$JUPYTER_PORT:$JUPYTER_PORT"
        - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
    env_file:
     - ./.env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=$JUPYTER_PORT --no-browser --allow-root
    
